apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-cloud-native-postgresql
  namespace: operators
spec:
  channel: stable-v1.18
  name: cloud-native-postgresql
  source: operatorhubio-catalog
  sourceNamespace: olm
